export const fellowshipResults = [
  {"id": "ITC10FF01", "name": "Sudeendra kumar K", "institute": "PES University, Bangalore", "city": "Bangalore", "state": "Karnataka"},
  {"id": "ITC10FF02", "name": "Sakthivel R", "institute": "Vellore Institute of Technology Vellore", "city": "Vellore", "state": "TAMILNADU"},
  {"id": "ITC10FF03", "name": "Vishal Gupta", "institute": "Vellore Institute of Technology, Vellore, India", "city": "Vellore", "state": "Tamil Nadu"},
  {"id": "ITC10FF04", "name": "Yasha Mallik", "institute": "B N M Institute of Technology", "city": "Bangalore", "state": "Karnataka"},
  {"id": "ITC10FF05", "name": "Geethu R S", "institute": "Amrita School of Engineering", "city": "Vallikavu", "state": "Kerala"},
  {"id": "ITC10FF06", "name": "DEBASIS DHAL", "institute": "Belda College", "city": "belda", "state": "West Bengal"},
  {"id": "ITC10FF07", "name": "Suhas Shirol", "institute": "Mangalore Institute of Technology and Engineering", "city": "Moodabidri", "state": "Karnataka"},
  {"id": "ITC10FF08", "name": "Suman Sau", "institute": "Siksha O Anusandhan University, Bhubaneswar", "city": "Bhubaneswar", "state": "Odisha"},
  {"id": "ITC10FF09", "name": "V. Muralidharan", "institute": "Dr. N.G.P. Institute of Technology", "city": "Coimbatore", "state": "Tamil Nadu"},
  {"id": "ITC10FF10", "name": "Dr. R. Umamaheswari", "institute": "Saveetha Engineering College", "city": "CHENNAI", "state": "Tamilnadu"},
  {"id": "ITC10FF11", "name": "Manas Ranjan Tripathy", "institute": "KIIT Deemed to be University, Bhubaneswar, Odisha", "city": "Bhubaneswar", "state": "Odisha"},
  {"id": "ITC10FF12", "name": "Silpa Kesav Velagaleti", "institute": "CVR College of Engineering", "city": "Hyderabad", "state": "Telangana"},
  {"id": "ITC10FF13", "name": "Manasa R", "institute": "Dayananda Sagar College of Engineering", "city": "Bengaluru", "state": "Karnataka"},
  {"id": "ITC10FF14", "name": "Krishna Kumar S.", "institute": "Federal Institute of Science and Technology", "city": "Angamaly", "state": "Kerala"},
  {"id": "ITC10FF15", "name": "Sujatha S. Kotabagi", "institute": "KLE Technological University", "city": "Hubballi", "state": "Karnataka"},
  {"id": "ITC10FR01", "name": "ARUN KUMAR N", "institute": "PES University", "city": "Bengaluru", "state": "Karnataka"},
  {"id": "ITC10FR02", "name": "Rahul Kumar", "institute": "IIT Bombay", "city": "Mumbai", "state": "Maharashtra"},
  {"id": "ITC10FR03", "name": "Rohit Badjatya", "institute": "Indian Institute of Technology Bombay", "city": "mumbai", "state": "Maharastra"},
  {"id": "ITC10FP01", "name": "Toushifraza Ramajan Darur", "institute": "Manipal School of Information Sciences", "city": "Belgavi", "state": "Karnataka"},
  {"id": "ITC10FP02", "name": "Uday C H", "institute": "Manipal School of Information Sciences", "city": "Bangalore", "state": "Karnataka"},
  {"id": "ITC10FF16", "name": "DINESHA P", "institute": "Dayananda Sagar College of Engineering", "city": "Bengaluru", "state": "KARNATAKA"},
  {"id": "ITC10FF17", "name": "Madhura Ramegowda", "institute": "Dayananda Sagar College of Engineering", "city": "Bengaluru", "state": "Karnataka"},
  {"id": "ITC10FF18", "name": "DINESH BABU A", "institute": "SRM Institute of Science and Technology, Vadapalani Campus", "city": "Chennai", "state": "Tamil Nadu"},
  {"id": "ITC10FF19", "name": "SREEKALA K S", "institute": "Saintgits College of Engineering Autonomous", "city": "Kottayam", "state": "Kerala"},
  {"id": "ITC10FR04", "name": "Shilpi Joshi", "institute": "SILVER OAK UNIVERSITY", "city": "Ahmedabad", "state": "Gujarat"},
  {"id": "ITC10FR06", "name": "RAMASANI ASWITHA", "institute": "Gayatri Vidya Parishad College of Engineering", "city": "Visakhapatnam", "state": "Andhra Pradesh"},
  {"id": "ITC10FR07", "name": "Meghana N", "institute": "IIT Dhanabd", "city": "Dhanbad", "state": "Jharkhand"},
  {"id": "ITC10FR08", "name": "Partha Sarathi Padhy", "institute": "National Institute of Technology Sikkim", "city": "Ravangala", "state": "Sikkim"},
  {"id": "ITC10FP03", "name": "Shaik Akram Ahamed", "institute": "SRM Institute of Science and Technology, Vadapalani Campus", "city": "Chennai", "state": "Tamil Nadu"},
  {"id": "ITC10FU02", "name": "SANJAY S SUBRAMANIAM", "institute": "IIIT Kottayam", "city": "Pala", "state": "Kerala"},
  {"id": "ITC10FU03", "name": "DHANYA S", "institute": "PSG Institute of Technology and Applied Reseach", "city": "Coimbatore", "state": "Tamil Nadu"},
  {"id": "ITC10FU04", "name": "Rakshit U Tadahal", "institute": "KLE Technological University", "city": "Hubbali", "state": "Karnataka"},
  {"id": "ITC10FU06", "name": "SATYAM KUAR", "institute": "Indian Institute of Technology Tirupati", "city": "Tirupati", "state": "Andhra Pradesh"},
  {"id": "ITC10FU07", "name": "Garv R Jain", "institute": "Vellore Institute of Technology", "city": "Vellore", "state": "Tamil Nadu"},
  {"id": "ITC10FU09", "name": "BALAJI R", "institute": "Sri Shakthi Institute of Engineering and Technology", "city": "Coimbatore", "state": "Tamil Nadu"},
  {"id": "ITC10FU11", "name": "Mohan Kumar S", "institute": "PSG College of Technology", "city": "Coimbatore", "state": "Tamil Nadu"},
  {"id": "ITC10FU12", "name": "Ann Theressa Babu", "institute": "Govt. Model Engineering College", "city": "Kochi", "state": "Kerala"},
  {"id": "ITC10FU13", "name": "Mukund Rathi", "institute": "IIIT Kottayam", "city": "Kottayam", "state": "Kerala"},
  {"id": "ITC10FU14", "name": "Shruti Murarilal Shakya", "institute": "NIELIT Aurangabad", "city": "Chhatrapati Sambhajinagar", "state": "MAHARASHTRA"},
  {"id": "ITC10FU15", "name": "Aaditya Sah", "institute": "Indian Institute of Technology Patna", "city": "Patna", "state": "Bihar"},
  {"id": "ITC10FU16", "name": "Siddanth Ganapathy K A", "institute": "PES University", "city": "Bengaluru", "state": "Karnataka"},
  {"id": "ITC10FU17", "name": "HARINI SRI S", "institute": "Dr N.G.P Institute of Technology", "city": "Coimbatore", "state": "Tamil Nadu"},
  {"id": "ITC10FU18", "name": "Kamalesh E", "institute": "Government College of Technology", "city": "Coimbatore", "state": "Tamil Nadu"},
];
